site_name: Documentación CEN
theme: readthedocs
nav:
  - Primeros Pasos: 
    - Coordinador Electrico: Primeros Pasos/Coordinador.md
    - Operación Real: Primeros Pasos/OpReal.md
    - Sistema de Información Pública: Primeros Pasos/sip.md
    - Instalación: Primeros Pasos/install.md
  - Manuales:
    - Creación Llaves: Manuales/Creacion_llaves.md
    - API's: Manuales/API.md
    - DevOps: Manuales/DevOps.md
    - Sanity Checks: Manuales/sanity_check.md
    - Soporte: Manuales/Soporte.md
  - Documentación Proyectos:
    - Donde buscar : Documentacion/busqueda.md
