site_name: Documentación CEN
theme: readthedocs
nav:
  - Primeros Pasos: 
    - Coordinador Electrico: Primeros Pasos/Coordinador.md
    - Operación Real: Primeros Pasos/OpReal.md
    - Sistema de Información Pública: Primeros Pasos/sip.md
    - Instalación: Primeros Pasos/install.md
  - Manuales:
    - Creación Llaves: Manuales/llaves.md