site_name: Documentación CEN
theme: readthedocs
nav:
  - Primeros Pasos: 
    - Coordinador Electrico: Primeros Pasos/Coordinador.md
    - Operación Real: Primeros Pasos/OpReal.md
    - Sistema de Información Pública: Primeros Pasos/sip.md
    - Instalación: Primeros Pasos/install.md
  - Manuales:
    - Creación Llaves: Primeros Pasos/Coordinador.md
    - API's: Primeros Pasos/Coordinador.md
    - DevOps: Primeros Pasos/Coordinador.md
    - Sanity Checks: Primeros Pasos/Coordinador.md
    - Soporte: Primeros Pasos/Coordinador.md1
  - Documentación Proyectos:
    - Cotas Despacho: Primeros Pasos/Coordinador.md
